[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "githubWorkflowsPypi"
version = "0.1.2"  # Aumentei para 0.1.2 para evitar conflito de versão no TestPyPI
description = "Um exemplo de publicação automatizada com GitHub Actions"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
authors = [
    { name="Isaac Silva", email="isaacsilvink@gmail.com" },
]

[tool.setuptools.packages.find]
where = ["."]
